-- ============================================================
-- V1__create_inbound_event.sql
-- Single table: audit log, deduplication, rejection tracking
-- ============================================================

CREATE TABLE IF NOT EXISTS inbound_event (
    id                  UUID            PRIMARY KEY,       -- UUIDv7 generated by application (time-ordered)
    cloudevents_id      VARCHAR(50)     NOT NULL,
    source              VARCHAR(100)    NOT NULL,
    type                VARCHAR(100)    NOT NULL,
    spec_version        VARCHAR(10)     NOT NULL DEFAULT '1.0',
    subject             VARCHAR(100),
    event_time          TIMESTAMPTZ,
    data_content_type   VARCHAR(50)     DEFAULT 'application/fhir+json',
    facility_id         VARCHAR(100),
    correlation_id      VARCHAR(100),
    source_event_id     VARCHAR(100),
    raw_payload         JSONB           NOT NULL,
    status              VARCHAR(20)     NOT NULL DEFAULT 'RECEIVED',
    rejection_reason    VARCHAR(50),
    error_details       TEXT,
    received_at         TIMESTAMPTZ     NOT NULL DEFAULT now(),

    -- Primary deduplication constraint
    CONSTRAINT uq_inbound_event_id_source UNIQUE (cloudevents_id, source)
);

-- Indexes for common query patterns
CREATE INDEX idx_inbound_event_subject    ON inbound_event (subject);
CREATE INDEX idx_inbound_event_source     ON inbound_event (source);
CREATE INDEX idx_inbound_event_status     ON inbound_event (status);
CREATE INDEX idx_inbound_event_received   ON inbound_event (received_at);
CREATE INDEX idx_inbound_event_rejection  ON inbound_event (rejection_reason) WHERE status = 'REJECTED';
