-- ============================================================
-- V1__create_inbound_event_log.sql
-- Single table: audit log, deduplication, rejection tracking
-- ============================================================

CREATE TABLE IF NOT EXISTS inbound_event_log (
    id                  UUID            PRIMARY KEY,       -- UUIDv7 generated by application (time-ordered)
    cloudevents_id      VARCHAR(50)     NOT NULL,
    source              VARCHAR(100)    NOT NULL,
    correlation_id      VARCHAR(100),
    raw_payload         JSONB           NOT NULL,
    status              VARCHAR(20)     NOT NULL DEFAULT 'RECEIVED',
    rejection_reason    VARCHAR(50),
    error_details       TEXT,
    received_at         TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),

    -- Primary deduplication constraint
    CONSTRAINT uq_inbound_event_log_id_source UNIQUE (cloudevents_id, source)
);

-- Indexes for common query patterns
CREATE INDEX idx_inbound_event_log_dedup      ON inbound_event_log (cloudevents_id, source, received_at);
CREATE INDEX idx_inbound_event_log_source     ON inbound_event_log (source);
CREATE INDEX idx_inbound_event_log_status     ON inbound_event_log (status);
CREATE INDEX idx_inbound_event_log_received   ON inbound_event_log (received_at);

-- Replica identity for logical replication (CDC)
ALTER TABLE inbound_event_log REPLICA IDENTITY FULL;
